[pytest]
DJANGO_SETTINGS_MODULE = config.settings.development
python_files = tests.py test_*.py *_tests.py
testpaths = backend
pythonpath = backend
addopts = --cov=backend --cov-report=html --cov-report=term-missing --strict-markers -v
markers =
    slow: marca tests que son lentos
    integration: marca tests de integración
